# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import time

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog

import Reader
import Writer
from HelpUI import UiHelp


class UiMainWindow(object):
    def __init__(self):
        self.ui = None
        self.helpwindow = None
        self.statusbar = None
        self.Logo = None
        self.Encode_progress = None
        self.Save_decoded_text = None
        self.Decode_progress = None
        self.Encoded_HTML_label = None
        self.Base_HTML_label = None
        self.label_6 = None
        self.Decode_prompt = None
        self.Encode_prompt = None
        self.Decode_Line_Edit = None
        self.Arrow_graphic = None
        self.Load_HTML = None
        self.Title_text = None
        self.HTML_sample = None
        self.Encode_Line_edit = None
        self.quit = None
        self.Load_encoded = None
        self.Save_encoded = None
        self.Help_button = None
        self.Encoded_sample = None
        self.Watermark = None
        self.Encode_button = None
        self.centralwidget = None
        self.Decode_button = None

    def setup_ui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(722, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.Decode_button = QtWidgets.QPushButton(self.centralwidget)
        self.Decode_button.setGeometry(QtCore.QRect(10, 250, 200, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Decode_button.sizePolicy().hasHeightForWidth())
        self.Decode_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Decode_button.setFont(font)
        self.Decode_button.setObjectName("Decode_button")

        self.Encode_button = QtWidgets.QPushButton(self.centralwidget)
        self.Encode_button.setGeometry(QtCore.QRect(10, 100, 200, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Encode_button.sizePolicy().hasHeightForWidth())
        self.Encode_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Encode_button.setFont(font)
        self.Encode_button.setAutoFillBackground(False)
        self.Encode_button.setObjectName("Encode_button")

        self.Watermark = QtWidgets.QLabel(self.centralwidget)
        self.Watermark.setGeometry(QtCore.QRect(0, 0, 74, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Watermark.setFont(font)
        self.Watermark.setTextFormat(QtCore.Qt.AutoText)
        self.Watermark.setOpenExternalLinks(False)
        self.Watermark.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Watermark.setObjectName("Watermark")

        self.Encoded_sample = QtWidgets.QTextEdit(self.centralwidget)
        self.Encoded_sample.setGeometry(QtCore.QRect(500, 100, 211, 411))
        self.Encoded_sample.setAutoFillBackground(False)
        self.Encoded_sample.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Encoded_sample.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Encoded_sample.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Encoded_sample.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.Encoded_sample.setReadOnly(True)
        self.Encoded_sample.setMarkdown("")
        self.Encoded_sample.setObjectName("Encoded_sample")

        self.Help_button = QtWidgets.QPushButton(self.centralwidget)
        self.Help_button.setGeometry(QtCore.QRect(10, 400, 200, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Help_button.sizePolicy().hasHeightForWidth())
        self.Help_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Help_button.setFont(font)
        self.Help_button.setObjectName("Help_button")

        self.Save_encoded = QtWidgets.QPushButton(self.centralwidget)
        self.Save_encoded.setGeometry(QtCore.QRect(530, 520, 75, 23))
        self.Save_encoded.setObjectName("Save_encoded")

        self.Load_encoded = QtWidgets.QPushButton(self.centralwidget)
        self.Load_encoded.setGeometry(QtCore.QRect(610, 520, 75, 23))
        self.Load_encoded.setObjectName("Load_encoded")

        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setGeometry(QtCore.QRect(109, 548, 75, 23))
        self.quit.setObjectName("quit")

        self.Encode_Line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.Encode_Line_edit.setGeometry(QtCore.QRect(10, 196, 200, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Encode_Line_edit.sizePolicy().hasHeightForWidth())
        self.Encode_Line_edit.setSizePolicy(sizePolicy)
        self.Encode_Line_edit.setMaxLength(60)
        self.Encode_Line_edit.setObjectName("Encode_Line_edit")

        self.HTML_sample = QtWidgets.QTextEdit(self.centralwidget)
        self.HTML_sample.setGeometry(QtCore.QRect(250, 100, 211, 411))
        self.HTML_sample.setAutoFillBackground(False)
        self.HTML_sample.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.HTML_sample.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.HTML_sample.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.HTML_sample.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.HTML_sample.setReadOnly(False)
        self.HTML_sample.setMarkdown("")
        self.HTML_sample.setObjectName("HTML_sample")

        self.Title_text = QtWidgets.QLabel(self.centralwidget)
        self.Title_text.setGeometry(QtCore.QRect(140, 30, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.Title_text.setFont(font)
        self.Title_text.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.Title_text.setObjectName("Title_text")
        self.Load_HTML = QtWidgets.QPushButton(self.centralwidget)
        self.Load_HTML.setGeometry(QtCore.QRect(315, 520, 75, 23))
        self.Load_HTML.setObjectName("Load_HTML")
        self.Arrow_graphic = QtWidgets.QLabel(self.centralwidget)
        self.Arrow_graphic.setGeometry(QtCore.QRect(465, 290, 30, 30))
        self.Arrow_graphic.setText("")
        self.Arrow_graphic.setPixmap(QtGui.QPixmap("convert-arrow.png"))
        self.Arrow_graphic.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Arrow_graphic.setObjectName("Arrow_graphic")

        self.Decode_Line_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.Decode_Line_Edit.setGeometry(QtCore.QRect(10, 344, 200, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Decode_Line_Edit.sizePolicy().hasHeightForWidth())
        self.Decode_Line_Edit.setSizePolicy(sizePolicy)
        self.Decode_Line_Edit.setReadOnly(True)
        self.Decode_Line_Edit.setObjectName("Decode_Line_Edit")

        self.Encode_prompt = QtWidgets.QLabel(self.centralwidget)
        self.Encode_prompt.setGeometry(QtCore.QRect(10, 180, 101, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.Encode_prompt.setFont(font)
        self.Encode_prompt.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Encode_prompt.setObjectName("Encode_prompt")

        self.Decode_prompt = QtWidgets.QLabel(self.centralwidget)
        self.Decode_prompt.setGeometry(QtCore.QRect(10, 330, 66, 13))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.Decode_prompt.setFont(font)
        self.Decode_prompt.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Decode_prompt.setObjectName("Decode_prompt")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(600, 10, 1, 1))
        self.label_6.setToolTipDuration(3)
        self.label_6.setObjectName("label_6")

        self.Base_HTML_label = QtWidgets.QLabel(self.centralwidget)
        self.Base_HTML_label.setGeometry(QtCore.QRect(250, 70, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Base_HTML_label.setFont(font)
        self.Base_HTML_label.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.Base_HTML_label.setObjectName("Base_HTML_label")

        self.Encoded_HTML_label = QtWidgets.QLabel(self.centralwidget)
        self.Encoded_HTML_label.setGeometry(QtCore.QRect(500, 70, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Encoded_HTML_label.setFont(font)
        self.Encoded_HTML_label.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.Encoded_HTML_label.setObjectName("Encoded_HTML_label")

        self.Decode_progress = QtWidgets.QProgressBar(self.centralwidget)
        self.Decode_progress.setGeometry(QtCore.QRect(11, 300, 233, 23))
        self.Decode_progress.setProperty("value", 0)
        self.Decode_progress.setFormat("")
        self.Decode_progress.setObjectName("Decode_progress")

        self.Save_decoded_text = QtWidgets.QPushButton(self.centralwidget)
        self.Save_decoded_text.setGeometry(QtCore.QRect(210, 344, 35, 21))
        self.Save_decoded_text.setObjectName("Save_decoded_text")

        self.Encode_progress = QtWidgets.QProgressBar(self.centralwidget)
        self.Encode_progress.setGeometry(QtCore.QRect(11, 150, 233, 23))
        self.Encode_progress.setProperty("value", 0)
        self.Encode_progress.setFormat("")
        self.Encode_progress.setObjectName("Encode_progress")

        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(10, 470, 100, 100))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("logo res.png"))
        self.Logo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Logo.setObjectName("Logo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)
        self.retranslate_ui(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Encode_button.clicked.connect(self.encode_text)
        self.Decode_button.clicked.connect(self.decode_text)
        self.Help_button.clicked.connect(self.open_help)
        self.Load_HTML.clicked.connect(self.load_html)
        self.Save_encoded.clicked.connect(self.save_encoded)
        self.Load_encoded.clicked.connect(self.load_encoded)
        self.Save_decoded_text.clicked.connect(self.save_plaintext)
        self.quit.clicked.connect(self.quitprog)

    def encode_text(self):
        plaintext = self.Encode_Line_edit.text()
        HTMLfile = self.HTML_sample.toPlainText()
        enctext = Writer.writer(plaintext, HTMLfile)
        self.Encode_progress.setValue(50)
        self.Encoded_sample.clear()
        self.Encoded_sample.insertPlainText(enctext)
        self.Encode_progress.setValue(100)
        time.sleep(2)
        self.Encode_progress.setValue(0)

    def decode_text(self):
        encfile = self.Encoded_sample.toPlainText()
        file = open('Stegdoc.html', 'w')
        file.write(encfile)
        file.close()
        self.Decode_progress.setValue(50)
        self.Decode_Line_Edit.clear()
        plain = Reader.reader()
        self.Decode_Line_Edit.insert(plain)
        self.Decode_progress.setValue(100)
        time.sleep(2)
        self.Decode_progress.setValue(0)

    def open_help(self):
        self.helpwindow = QtWidgets.QDialog()
        self.ui = UiHelp()
        self.ui.setup_ui(self.helpwindow)
        self.helpwindow.show()

    def load_html(self):
        file_filter = 'html File (*.html *.HTML);; Text File (*.txt)'
        filename = QFileDialog.getOpenFileName(
            caption='Select a .HTML or .txt file',
            filter=file_filter,
            initialFilter='html File (*.html *.HTML)'
        )
        directory = filename[0]

        with open(directory, "r") as f:
            text = f.read()
            self.HTML_sample.clear()
            self.HTML_sample.insertPlainText(text)

    def save_encoded(self):
        filename = QFileDialog.getSaveFileName(
            caption='Select a location to save encoded results',
            filter='Text File (*.txt)'
        )

        directory = filename[0]

        with open(directory, 'w') as f:
            text = self.Encoded_sample.toPlainText()
            f.write(text)

    def save_plaintext(self):
        filename = QFileDialog.getSaveFileName(
            caption='Select a location to save plaintext',
            filter='Text File (*.txt)'
        )

        directory = filename[0]

        with open(directory, 'w') as f:
            text = self.Decode_Line_Edit.text()
            f.write(text)

    def load_encoded(self):
        file_filter = 'html File (*.html *.HTML);; Text File (*.txt)'
        filename = QFileDialog.getOpenFileName(
            caption='Select a .HTML or .txt file',
            filter=file_filter,
            initialFilter='html File (*.html *.HTML)'
        )
        directory = filename[0]

        with open(directory, "r") as f:
            text = f.read()
            self.Encoded_sample.clear()
            self.Encoded_sample.insertPlainText(text)

    @staticmethod
    def quitprog():
        quit(0)

    def retranslate_ui(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HTML Encoder/Decoder"))
        self.Decode_button.setToolTip(_translate("MainWindow",
                                                 "<p><body><html>Decodes the given encoded text from the furthest "
                                                 "box</p></body></html>"))
        self.Decode_button.setText(_translate("MainWindow", "Decode"))
        self.Encode_button.setToolTip(
            _translate("MainWindow", "<p><body><html>Encodes your given text from the form below</p></body></html>"))
        self.Encode_button.setText(_translate("MainWindow", "Encode"))
        self.Watermark.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>(https://github.com/Ju5t-j1m/Y4project)</p></body></html>"))
        self.Watermark.setText(_translate("MainWindow", "v3.0 HSED J.N"))
        self.Encoded_sample.setHtml(_translate("MainWindow",
                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                               "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style "
                                               "type=\"text/css\">\n "
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; "
                                               "font-size:8.25pt; font-weight:400; font-style:normal;\">\n "
                                               "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                                               "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                                               "-qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Encoded_sample.setPlaceholderText(_translate("MainWindow", "Your encoded HTML text will appear here..."))
        self.Help_button.setText(_translate("MainWindow", "About/Help"))
        self.quit.setText(_translate("MainWindow", "Quit"))
        self.Save_encoded.setText(_translate("MainWindow", "Save"))
        self.Load_encoded.setText(_translate("MainWindow", "Load"))
        self.Encode_Line_edit.setToolTip(_translate("MainWindow",
                                                    "<p><body><html>Permitted characters (a-z, A-Z, 0-9, \' \', "
                                                    "\'!\', \'$\', \'%\', \'&\', \'*\', \'(\', \')\', \':\', \';\', "
                                                    "\'-\', \'+\', \'=\', \'?\', \'@\', \'.\')</p></body></html>"))
        self.Encode_Line_edit.setPlaceholderText(_translate("MainWindow", "Enter text to encode..."))
        self.HTML_sample.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                            "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style "
                                            "type=\"text/css\">\n "
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; "
                                            "font-size:8.25pt; font-weight:400; "
                                            "font-style:normal;\">\n "
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; "
                                            "margin-left:0px; margin-right:0px; "
                                            "-qt-block-indent:0; text-indent:0px;\"><br "
                                            "/></p></body></html>"))
        self.HTML_sample.setPlaceholderText(_translate("MainWindow", "Your base HTML will appear here once "
                                                                     "loaded....(To be encoded)"))
        self.Title_text.setText(_translate("MainWindow", "HTML Steganography Encoder & Decoder V3.0"))
        self.Load_HTML.setText(_translate("MainWindow", "Load"))
        self.Decode_Line_Edit.setToolTip(_translate("MainWindow", "<p><body><html>The result of "
                                                                  "decoding</p></body></html>"))
        self.Decode_Line_Edit.setPlaceholderText(_translate("MainWindow", "..."))
        self.Encode_prompt.setText(_translate("MainWindow", "Text to encode..."))
        self.Decode_prompt.setText(_translate("MainWindow", "Decoded text"))
        self.label_6.setToolTip(_translate("MainWindow", "<p><body><html>I\'ll never forgive QTdesigner if they\'ve "
                                                         "wiped the stegText</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "l"))
        self.Base_HTML_label.setText(_translate("MainWindow", "Base HTML"))
        self.Encoded_HTML_label.setText(_translate("MainWindow", "Encoded HTML"))
        self.Save_decoded_text.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    w = QtWidgets.QMainWindow()
    ui = UiMainWindow()
    ui.setup_ui(w)
    w.show()
    sys.exit(app.exec_())
